export const EXPENSE_CATEGORIES = [
  { key: 1, text: "Others" },
  { key: 2, text: "Bank fees" },
  { key: 3, text: "Rent" },
  { key: 4, text: "Travel" },
  { key: 5, text: "Telephone" },
  { key: 6, text: "Client gifts" },
  { key: 7, text: "Office expenses and supplies" },
  { key: 8, text: "Insurance" },
  { key: 9, text: "Maintenance and repairs" },
  { key: 10, text: "Legal and professional expenses" },
  { key: 11, text: "Advertising" },
  { key: 12, text: "Licenses and permits" },
  { key: 13, text: "Utilities" },
  { key: 14, text: "Business meals" },
  { key: 15, text: "Course" },
  { key: 16, text: "Credit and collection fees" },
  { key: 17, text: "Subscriptions" },
  { key: 18, text: "Moving expenses" },
  { key: 19, text: "Software" },
  { key: 20, text: "Medical expenses" },
] as const;
